name: kt_dart
description: This project is a port of kotlin-stdlib for Dart/Flutter projects. It includes collections (KtList, KtMap, KtSet) with 150+ methods as well as other useful packages.
version: 1.1.0
repository: https://github.com/passsy/kt.dart
issue_tracker: https://github.com/passsy/kt.dart/issues

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  meta: ^1.5.0

dev_dependencies:
  lint: ^1.5.3
  test: ^1.17.12
